### PR TITLE
tee-supplicant: fix gcc warning

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Fixes gcc warning:
src/tee_socket.c: In function 'poll_with_timeout.constprop':
src/tee_socket.c:361:28: error: 'until.tv_nsec' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  diff.tv_nsec = a->tv_nsec - b->tv_nsec;
                 ~~~~~~~~~~~^~~~~~~~~~~~
src/tee_socket.c:382:18: note: 'until.tv_nsec' was declared here
  struct timespec until;
                  ^~~~~
src/tee_socket.c:360:26: error: 'until.tv_sec' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  diff.tv_sec = a->tv_sec - b->tv_sec;
                ~~~~~~~~~~^~~~~~~~~~~
src/tee_socket.c:382:18: note: 'until.tv_sec' was declared here
  struct timespec until;
                  ^~~~~
cc1: all warnings being treated as errors

Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
Will this work with some GCC 4.9? https://github.com/OP-TEE/optee_test/pull/254

**Comment by jenswi-linaro** [comment]
This should take care of that.

**Comment by jforissier** [comment]
I think it should, thanks.

`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
Squashed and tag applied
